### ISSUE TITLE
Yarn -  options.allowedHosts[0]

### ISSUE THREAD

**Issue by STACKL0RD** [oar-team/oar-docker-compose#12]
@adfaure @augu5te

When I try to launch dashboard with `yarn start`, I receive the following problem:

```UNIX
$ yarn start
yarn run v1.22.19
$ react-scripts start --host localhost
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.
error Command failed with exit code 1.
```

In my first terminal, my containers run correctly.
In my second terminal, I changed the proxy address in `package.json`, then I execute my frontend with the following line:

```UNIX
docker exec --user oar --env OARCONFFILE=/etc/oar/oar.conf dev_frontend_1 uvicorn oar.api.app:app --port 8001 --host 0.0.0.0
```

In my third terminal, I tried to launch dashboard like I said previously.

**More information:**
I have these dependencies in `package.json`:

```JSON
"dependencies": {
    "@babel/core": "7.21.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "babel-preset-jest": "29.5.0",
    "babel-preset-react-app": "10.0.1",
    "cors": "^2.8.5",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-admin": "^3.2.3",
    "react-dom": "^16.12.0",
    "react-scripts": "5.0.1",
    "typescript": "~3.7.2",
}
```
and these scripts:

```JSON
"scripts": {
    "start": "react-scripts start --host localhost",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
 }
```

**Comment by augu5te** [comment]
Do you have tested some recommended solutions ? Like showed in 
https://stackoverflow.com/questions/70374005/invalid-options-object-dev-server-has-been-initialized-using-an-options-object/70413065#70413065
Add options section in package.json :
`"options": {
    "allowedHosts": ["localhost", ".localhost"],
    "proxy": "https://localhost:3386/"
  }
`
Note: number port must be adapted

or use a proxy package like `http-proxy-middleware`

**Comment by STACKL0RD** [comment]
Thanks for your response. That works.
